<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>false</SelfContained>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\OverlayApp\bin\Release\net8.0-windows10.0.19041.0\publish\SystemCoreHost.exe" Link="Resources\SystemCoreHost.exe" />
  </ItemGroup>

</Project>
